/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smol-ame-in-an-upcycled-terrarium-hololiveen-490cecc249d242188fda5ad3160a4b24
Title: Smol Ame in an Upcycled Terrarium [HololiveEn]
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { Group, Mesh, SkinnedMesh } from 'three';
import { ReactThreeFiber } from '@react-three/fiber';

interface ModelProps extends ReactThreeFiber.Object3DNode<Group, typeof Group> {}

export function Model(props: ModelProps) {
  const group = useRef<Group>(null)
  const { nodes, materials } = useGLTF('assets/3d/scene.gltf') as any

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 3, 0, 0]}>
              <group name="pasokon_1">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={(nodes.Object_4 as Mesh).geometry}
                  material={materials.pasokon}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={(nodes.Object_5 as Mesh).geometry}
                  material={materials.terrarium1}
                />
              </group>
              <group name="amelia_37" position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_10"
                    geometry={(nodes.Object_10 as SkinnedMesh).geometry}
                    material={materials.terrarium1ame}
                    skeleton={(nodes.Object_10 as SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={(nodes.Object_12 as SkinnedMesh).geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={(nodes.Object_12 as SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    name="Object_37"
                    geometry={(nodes.Object_37 as SkinnedMesh).geometry}
                    material={materials.terrarium1ame}
                    skeleton={(nodes.Object_37 as SkinnedMesh).skeleton}
                    morphTargetDictionary={(nodes.Object_37 as SkinnedMesh).morphTargetDictionary}
                    morphTargetInfluences={(nodes.Object_37 as SkinnedMesh).morphTargetInfluences}
                  />
                </group>
              </group>
              <group
                name="isopod002_49"
                position={[0, 0.864, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.073}>
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <skinnedMesh
                    name="Object_65"
                    geometry={(nodes.Object_65 as SkinnedMesh).geometry}
                    material={materials.terrarium1}
                    skeleton={(nodes.Object_65 as SkinnedMesh).skeleton}
                  />
                  <skinnedMesh
                    name="Object_67"
                    geometry={(nodes.Object_67 as SkinnedMesh).geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={(nodes.Object_67 as SkinnedMesh).skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('assets/3d/scene.gltf');
